sonar.projectKey=philjohnson74_pmg-presence
sonar.organization=philjohnson74
sonar.projectName=PMG Presence

sonar.sources=apps/api/src,packages/contracts/src,packages/ui/src
sonar.tests=apps/api/test
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.d.ts

sonar.javascript.lcov.reportPaths=apps/api/coverage/lcov.info
sonar.typescript.tsconfigPaths=apps/api/tsconfig.build.json,packages/contracts/tsconfig.json,packages/ui/tsconfig.json
