import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import { App } from './app.js';
import { registerSW } from 'virtual:pwa-register';

// Register the Workbox service worker (generated by vite-plugin-pwa).
// skipWaiting: true means the new SW activates immediately without waiting
// for all tabs to close, so marshals always get the latest app shell.
registerSW({ immediate: true });

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
